### ISSUE TITLE
Header values sometimes incorrectly treated as Dates

### ISSUE THREAD

**Issue by tombailey** [Lissy93/web-check#1]
I noticed that some header values don't show correctly. For example, when I analyzed https://google.co.uk, the `HeadersCard` shows:

```text
cache-control    1 January 2000
content-type    1 January 8859
```

I noticed the lambda function for the headers is returning the correct data:
```json
{
  "date": ["Sat, 15 Jul 2023 06:17:25 GMT"],
  "expires": ["-1"],
  "cache-control": ["private, max-age=0"],
  "content-type": ["text/html; charset=ISO-8859-1"],
  ...
}
```

Digging deeper, I saw the Row component has both a title attribute and inner text for data. The HTML looks like this:
```html
<div class="sc-cPiKLX iEeoJy">
  <span class="lbl">cache-control</span>
  <span class="val" title="private, max-age=0">1 January 2000</span>
</div>
```

The title is correct but the inner text is not.

It appears `isValidDate(new Date(value))` of `formatValue` within the Row component is causing the problem:
https://github.com/Lissy93/web-check/blob/master/src/components/Form/Row.tsx#L72

Constructing a new Date with these header values produces a Date that is considered valid, hence the inner text is incorrectly formatted as a date.
```js
console.log(new Date(["private, max-age=0"]));
// Sat Jan 01 2000 00:00:00 GMT+0900 (Japan Standard Time)

new Date('private, max-age=0')
// Sat Jan 01 2000 00:00:00 GMT+0900 (Japan Standard Time)
```

I created the following code sandbox to demonstrate the failing cases:
https://codesandbox.io/p/sandbox/unruffled-austin-lhypg6?file=%2Findex.test.ts%3A45%2C51

Perhaps something like [js-http-date](https://github.com/rxbryan/js-http-date) could help resolve the issue?

**Comment by Lissy93** [comment]
Thanks @tombailey for your detailed breakdown, this should be resolved now :)
