### ISSUE TITLE
Feature request: Create a report in PDF format

### ISSUE THREAD

**Issue by Natgho** [Lissy93/web-check#112]
The product is very good, but instead of the reports being temporary and recalculated every time, wouldn't it be great if you put the "download" button somewhere and we could download the current version of the report as a PDF?

**Comment by Lissy93** [comment]
There is a download option, if you scroll down to the bottom ;)
#107

**Comment by Natgho** [comment]
@Lissy93 ?

**Comment by Lissy93** [comment]
Yeah, so you can use that Json to generate a report in any format you like, PDF, Markdown, LaTex using a scripting language of your choice.

Is that what you meant?

**Comment by Natgho** [comment]
Think simpler please: 

1. user clicks on the "Download Report as PDF" button.
2. Everything that appears on the page is put into a PDF file and downloaded.

There is no need to create a report using a script, this interface is already like a report, all that needs to be done is to customize the ability to print with CTRL + P a bit more (for example, it would be good if the "External Tools for Further Research" section at the bottom is not in the report) and assign it to a button.

**Comment by Natgho** [comment]
@Lissy93 ?

**Comment by Natgho** [comment]
Actually I tried, but my specialty is backend and Python, so I could not finalize it. I looked at the source code and it looked like poetry :) so I didn't want to break it by making a bad patch.
