### ISSUE TITLE
Trace route Leak

### ISSUE THREAD

**Issue by klisza1993** [Lissy93/web-check#119]
Trace route leaks host IPs, Public, docker and edge router gateway..

eg. 172.16.0.6(Docker image) --> 10.0.0.1(internal lan router ip) -->  1.1.1.1(my pub ip) ......[more ips]

**Comment by klisza1993** [comment]
Am I Able to disable trace router?

**Comment by Lissy93** [comment]
You could remove that check, if you don't need it. Just delete the file
