### ISSUE TITLE
Clarification on Using web-check with GPL v3 Licensed Wappalyzer for Commercial SaaS

### ISSUE THREAD

**Issue by Giova200** [Lissy93/web-check#148]
Hi,

I’m using web-check, which is released under the MIT license. I see that it integrates Wappalyzer, which is licensed under GPL v3. I have a few concerns about using this combination for a commercial SaaS application:

Can I use web-check with Wappalyzer integrated for a commercial SaaS application without violating the GPL v3 license?
What are the implications of the GPL v3 license on Wappalyzer for my usage in a SaaS model?
Are there any specific compliance steps I need to follow to ensure that I am not infringing on the GPL v3 license terms?
I would greatly appreciate any clarification or guidance on this matter.

Thank you!

**Comment by Lissy93** [comment]
Hi,
At the moment, it's not possible to use Web Check commercially because of it's use of some dependencies. 
I will be working on a future version, which should mitigate some of that

**Comment by Giova200** [comment]
Is there smth like a list of the ones (scans using api(without any non commercially avaiable depenencies?

**Comment by Lissy93** [comment]
Yes, in our SBOM.
But for this version of web check, the commercial licenses are quite ingrained, so you'd only be able to use for personal use.

I am rebuilding parts of it which should resolve a lot of those issues, as I'm deploying a SaaS version in the next few weeks.
