### ISSUE TITLE
feature request check if dns blocked

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [Lissy93/web-check#15]
check against the following dns resolver if dns entry is blocked:

adguard.com Favicon  AdGuard (176.103.130.130)
adguard.com Favicon  AdGuard Family (176.103.130.132)
cleanbrowsing.org Favicon  CleanBrowsing Adult (185.228.168.10)
cleanbrowsing.org Favicon  CleanBrowsing Family (185.228.168.168)
cleanbrowsing.org Favicon  CleanBrowsing Security (185.228.168.9)
cloudflare.com Favicon  CloudFlare (1.1.1.1)
cloudflare.com Favicon  CloudFlare Family (1.1.1.3)
comodo.com Favicon  Comodo Secure (8.26.56.26)
google.com Favicon  Google DNS (8.8.8.8)
neustar.com Favicon  Neustar Family (156.154.70.3)
neustar.com Favicon  Neustar Protection (156.154.70.2)
symantec.com Favicon  Norton Family (199.85.126.20)
opendns.com Favicon  OpenDNS (208.67.222.222)
opendns.com Favicon  OpenDNS Family (208.67.222.123)
quad9.net Favicon  Quad9 (9.9.9.9)
yandex.com Favicon  Yandex Family (77.88.8.7)
yandex.com Favicon  Yandex Safe (77.88.8.88)

**Comment by Lissy93** [comment]
Implemented  in 519d2f0f791aa99c0cd00898f300a430f3e63dd9 & 6b8c50a9aaf0dfaf8c1a53df596fbe1302aa9d74 :)

![screenshot](https://github.com/Lissy93/web-check/blob/master/.github/screenshots/tiles/block-lists.png?raw=true)
