### ISSUE TITLE
FindIpButton' is assigned a value but never used, findIpAddress' is assigned a value but never used

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [Lissy93/web-check#16]
- Line 41:7:   'FindIpButton' is assigned a value but never used   @typescript-eslint/no-unused-vars
- Line 129:9:  'findIpAddress' is assigned a value but never used  @typescript-eslint/no-unused-vars

**Comment by adminlove520** [comment]
me too

**Comment by Lissy93** [comment]
Closing as fixed :)
