### ISSUE TITLE
docker install for oracel linux r8.8 Unable open 8888 for web why?

### ISSUE THREAD

**Issue by cddisk2000** [Lissy93/web-check#20]
System environment: Oracel Linux R8.8

Installation steps
1. Download web check git hub
2. Current directory execution => docker compose up -d
![image](https://github.com/Lissy93/web-check/assets/32296520/527ba625-c2f9-464b-a981-0b8fbc1533a9)

3. netstat -ltunp  check port
![image](https://github.com/Lissy93/web-check/assets/32296520/15e8f5df-5615-4dff-904c-fbca3e59ac73)

4. docker ps  check container
![image](https://github.com/Lissy93/web-check/assets/32296520/bc2b5353-0ee4-40c2-b2b6-5108817656c5)

5. Use chrome and firefox browser Unable to open webpage 
http://ip:8888

Error Message

Unable to reach this site 192.168.2.12 rejected our connection request.
Please try the following:

check network connection
Check proxy servers and firewalls
ERR_CONNECTION_REFUSED

#==== Additional commands

#Open tcp 8888 firewall 
sudo firewall-cmd --add-port=8888/tcp --permanent
sudo firewall-cmd --reload

#Close Selinux
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
setenforce 0

**Comment by gso-trifork-security** [comment]
For me the service is listening on port 3000, I don't know why the documentation says 8888.

**Comment by cddisk2000** [comment]
> For me the service is listening on port 3000, I don't know why the documentation says 8888. I have created a PR to fix this: #32

Modify docker composite. yml

version: '3.9'
services:
  web-check:
    container_name: Web-Check
    image: lissy93/web-check
    ports:
      - 8888:3000
    restart: unless-stopped
    
    
    Thank you for your help
