### ISSUE TITLE
Can not use for non well-known ports

### ISSUE THREAD

**Issue by sujunmin** [Lissy93/web-check#21]
Hi, I tested the web site for https port 8443, there was an error for it.
<img width="801" alt="image" src="https://github.com/Lissy93/web-check/assets/6415168/00094152-079f-4938-b1b0-c908291e57cc">

**Comment by lyca-knight** [comment]
Enter the URL without Port at the end.
It checks for open / closed Ports.
But 8443 is not in the list. It could be added in the check-ports.js file.
![image](https://github.com/Lissy93/web-check/assets/55512972/38b442cc-b8b6-4384-926d-6d27abc6f50c)

**Comment by Lissy93** [comment]
I need to find a better way of checking open/closed ports, that doesn't involve iterating through them all. 

Right now, I get charged based on compute time, so if I go through 100+ ports, that's going to take a few seconds, and the cost of running that (for 100k users/month) will add up quickly. That's the reason that it's currently only checking for the most common ports, as they do the job in 85% of use cases.

I'm open to suggestions, if anyone knows a sustainable way to do this?

**Comment by Samkit-shah** [comment]
Can we give an additional option to user to add ports that the user wishes to be checked for!
If so we can scan those ports giving customization to the scan.

I can work on this!

**Comment by sujunmin** [comment]
I've test for non well-known ports and that is ok.
