### ISSUE TITLE
[Headers -> content-type] The value of 'content-type' is being displayed as a Date type

### ISSUE THREAD

**Issue by ya-luotao** [Lissy93/web-check#22]
![CleanShot 2023-08-04 at 14 04 06@2x](https://github.com/Lissy93/web-check/assets/7478427/73736427-01ab-4351-a126-57428ff5f890)

**Comment by muni106** [comment]
can you share more information i.e. which url you used and the method used to run the application

**Comment by ya-luotao** [comment]
Hey @muni106 I discovered the issue on: https://web-check.as93.net/results/https%3A%2F%2Ftime.com

**Comment by muni106** [comment]
I've tried to run "time.com" in different ways and it is as it should be (the image) even with your link, i think it could be a cache error or something similar.

**Comment by ya-luotao** [comment]
That's weird... okay I think it could be a caching issue. Thanks!

**Comment by dizorg** [comment]
It still happens: 

<img width="1246" height="310" alt="Image" src="https://github.com/user-attachments/assets/5b3f2160-7fe2-4782-a672-8fdbe2df6c0b" />
