### ISSUE TITLE
ip reverse lookup domain name

### ISSUE THREAD

**Issue by Pantyhose-X** [Lissy93/web-check#25]
* Reverse query all domain names bound to ip according to ip

example：web-check.xyz  
[![alt text](https://github-production-user-asset-6210df.s3.amazonaws.com/42504385/258705734-58c25381-92ef-470d-913f-e56e29c34c16.PNG "title")](https://ipchaxun.com/web-check.xyz/)

---
---
[![alt text](https://user-images.githubusercontent.com/42504385/258706695-184608a0-1901-49d7-8c12-a6e230edee78.PNG "title")](https://ipchaxun.com/web-check.xyz/)

### demo site
https://ipchaxun.com/web-check.xyz/

**Comment by Lissy93** [comment]
Do you have some more info / English version?
Or an idea of how to implement such a feature with is computationally efficient, or know of an API I can integrate with which isn't overly expensive?

I'm happy to re-open if anyone has any suggestions of an effective implementation.

**Comment by Pantyhose-X** [comment]
> Do you have some more info / English version? Or an idea of how to implement such a feature with is computationally efficient, or know of an API I can integrate with which isn't overly expensive?
> 
> I'm happy to re-open if anyone has any suggestions of an effective implementation.

English version https://dnsdblookup.com/

**Comment by Lissy93** [comment]
But no API? 
For this to work, I need to find a method to find the data which is computationally efficient, or find an API which isn't overly expensive.
