### ISSUE TITLE
Out of the box issues

### ISSUE THREAD

**Issue by acandare** [Lissy93/web-check#33]
I tried the tool via docker using the following command
`docker run -p 8888:3000 --network host lissy93/web-check`
When doing a webcheck, it only shows 1 successful job  (cookies) out of the box. 

The rest of the error shows the following:

Error Details for get-ip
The get-ip job failed with an error state after 417 ms. The server responded with the following error:
Cannot read properties of undefined (reading 'error')

Error Details for headers
The headers job failed with an error state after 614 ms. The server responded with the following error:

Failed to get a valid response 😢
This is likely due the target not exposing the required data, or limitations in how Netlify executes lambda functions, such as the 10-sec timeout.
Error info:
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Tried adding the following Environment variables - TORRENT_IP_API_KEY, REACT_APP_SHODAN_API_KEY, REACT_APP_WHO_API_KEY, SECURITY_TRAILS_API_KEY and BUILT_WITH_API_KEY with their API key but still shows 1 job successful. 

Tried deploying the app via docker (portainer) and via ubuntu using the above commands. 
![webcheck](https://github.com/Lissy93/web-check/assets/35393779/0d566667-887d-474f-ba9f-d41b70d3d20d)

**Comment by t3chn0m4g3** [comment]
@Lissy93 I have the same issue, seems to be a regression of #11 introduced with https://github.com/Lissy93/web-check/commit/0fd0e537f7b74f2ce75dbb3c02d820152d8d7dae change of the `Dockerfile`.

**Comment by acandare** [comment]
What do I need to do to fix the issue? Thanks.

**Comment by bcdurden** [comment]
I'm having the same issue as above while running in RKE2. I have a few valid API tokens in there but neither container image works (dockerhub or ghcr hosted).

**Comment by Lissy93** [comment]
I'm going to take a look at the Dockerfile now.
I think it's using the wrong start command, as yarn start only spins up the GUI, not the API, so all checks fail.

In the meantime, just running `yarn build && yarn serve` will get things working.
Here's the steps to get the app running:

```bash
git clone https://github.com/Lissy93/web-check.git # Grab the code
cd web-check # Move into the project directory
yarn install # Install dependencies
yarn build # Build the app for production
yarn serve # Start the app (API and GUI)
```

Alternatively, if you're hosting on Netlify you can just [click here](https://app.netlify.com/start/deploy?repository=https://github.com/lissy93/web-check) to spin up a fresh instance of the app.

**Comment by Lissy93** [comment]
I've pushed an update to the Dockerfile which fixes this now :)
Just re-pull the latest image and run: `docker run -p 3000:3000 lissy93/web-check`

**Comment by Lissy93** [comment]
I just noticed, but in your screenshot, there's no URL specified. If you go back to the homepage and enter a url, then try again.

The environmental variables / API keys shouldn't be required for the app to run, as most the results come from analyzing native HTTP requests. You'll just get access to some extra data if they're specified.

![image](https://github.com/Lissy93/web-check/assets/1862727/567b91bc-5659-4cdc-b430-38d8b618cb54)
