### ISSUE TITLE
Dns values are missplaced

### ISSUE THREAD

**Issue by Gottarocket** [Lissy93/web-check#4]
I believe the css or style is doing it but I may be wrong. If you check your screenshot about how tool works you can see A record value showing an IP address which is fine but AAAA  values should be alphanumeric i.e. it should show ipv6 address not ip4. Some missing Ipv4 addresses in A record are shown in AAAA. So current values of AAAA should be in A record. Going forward, MX record is missing. Its not mentioned anywhere. Instead it shows AAAA value which it should have shown under AAAA. CNAME too is missing. Its showing Nameservers value instead. Txt record is the one that works and showing up at exact place . Please do correct it. Anyways nice ui

**Comment by Lissy93** [comment]
Closing as dup of #35

See: https://github.com/Lissy93/web-check/issues/35#issuecomment-1678755421 :)
