### ISSUE TITLE
Missing Error Handling in Express Routes:

### ISSUE THREAD

**Issue by 0x5FE** [Lissy93/web-check#42]
It is advisable to enclose the asynchronous segments of your code within a try...catch block in order to effectively manage and address any potential errors that may arise. I made an example:

![test](https://github.com/Lissy93/web-check/assets/65371336/226e148a-2115-4a13-81ed-0c8a1a2b09f9)

**Comment by Lissy93** [comment]
Already is ;)

https://github.com/Lissy93/web-check/blob/7559716c5de20ad9d95b1d2a403a9df86d2d7d25/server.js#L40-L47
