### ISSUE TITLE
Usability / user hints

### ISSUE THREAD

**Issue by sponsoredlinks** [Lissy93/web-check#49]
Hi, thanks for a nice tool. This is really more about usability than any actual issue, but it may be worth trying to tie the description/mitigation details in with the actual errors

eg for a test website I used, the help dialog (1) could possibly break categories to a new line and (2) hides the original errors for that category

I appreciate you don't want to spend endless time on this but a hover and click (over individual errors) interface would be much nicer to use - or perhaps just a separate summary of detected insecurities along with info/mitigation inline

Either way thanks again this is great to use compared to the myriad of non-overlapping other tools in this space..

![image](https://github.com/Lissy93/web-check/assets/4774006/5f049d58-9cee-4156-a265-4e7e4dc039af)

**Comment by Lissy93** [comment]
Yeah, I agree that would be useful

Only thing is, a lot of the results are very data driven - I'm checking if a bunch of things exist, and displaying a True / False, for each. So the hints would need to be manually added, which would probably be quite a bit of work.

**Comment by sponsoredlinks** [comment]
Sorry, I may not have described the suggestion well - I just meant to present the relevant part of the info you already do display as an on-hover over the individual items. 

I guess it seems that if the test and result display are data-driven then can a static docstr (itself also data?) be embedded along with this easily

Again no problems if this is indeed hard, just clarifying in case of misunderstanding
