### ISSUE TITLE
Chromium and traceroute tests failing

### ISSUE THREAD

**Issue by nmccouat** [Lissy93/web-check#50]
eg 
![image](https://github.com/Lissy93/web-check/assets/4774006/b8aaff4d-c281-4b6d-9ab0-2bcb2078f230)

Also blocklists 

![image](https://github.com/Lissy93/web-check/assets/4774006/1764dd4a-0472-4805-9c45-9acfb4bd067e)

& status (although may be the website. It might be worth adding a configurable timeout for slow websites

![image](https://github.com/Lissy93/web-check/assets/4774006/a4a40ec6-073e-4bff-a850-8c12a3fdc56f)

**Comment by nmccouat** [comment]
Traceroute (partially redacted) 
![image](https://github.com/Lissy93/web-check/assets/4774006/d2f679f1-3587-4c23-b1f8-74d4bec8d938)

**Comment by Lissy93** [comment]
Hiya @nmccouat

I pushed an update (in 5297b2ffe793ae1ff4741cb243c99a09f4f4bd40) which fixes the block-lists job.

For traceroute, you need to have the `traceruote` command installed in the environment you're running web-check (e.g. container, vm or host). Same for the tech stack job, but with Chromium - if it's installed in a non-standard location, you can set the `CHROME_PATH` env var, to point to the bin, and that should work :)

**Comment by sponsoredlinks** [comment]
Hi, sorry, I wasn't 100% clear in describing this issue - these problems are occuring on the example server (https://web-check.xyz/)

Understood if it's not intended that they work, it might be worth putting in a placeholder message saying so if so
