### ISSUE TITLE
Show subdomains for a domain

### ISSUE THREAD

**Issue by fordnox** [Lissy93/web-check#56]
https://www.subdomain.center/

adding this functionality would be a great addition for web check.

**Comment by Lissy93** [comment]
I think this has been mentioned before, but there's no way to find all subdomain for a given domain really (unless iterating over common domains, which would be too computationally expensive, and probably against ToS for most sites). I've also not come across an API which does this effectively and isn't too over-priced. 

If you've got suggestions of how this may be implemented in a sustainable way, I'd be happy to re-open.

**Comment by fordnox** [comment]
I agree that it is not possible to find _all_ subdomains, still there are some ways to do it, which in most cases is enough.

Somehow these tools find subdomains:
* https://www.vedbex.com/subdomain-finder/aliciasykes.com
* https://securitytrails.com/blog/subdomain-finder

<img width="1443" alt="Screenshot 2023-09-28 at 16 11 16" src="https://github.com/Lissy93/web-check/assets/398619/193ab17f-e49e-4a24-a656-6e8fa2d6fd2f">

<img width="1580" alt="Screenshot 2023-09-28 at 16 16 08" src="https://github.com/Lissy93/web-check/assets/398619/7008984a-9303-4883-8ef3-a3a4283b2732">

**Comment by Lissy93** [comment]
Yes, but they do it by scanning for subdomains - I don't have enough compute to do that inexpensivley.
Security Trails do have an API, but again - it's too costly (it [starts at $500/month](https://securitytrails.com/corp/pricing)).

If I had more cash, I'd add this, but as  it stands running Web-Check is already costing me more than I expected :/

**Comment by fordnox** [comment]
got it, thanks for reply ;)
