### ISSUE TITLE
Can't install on Raspberry pi4 via Docker

### ISSUE THREAD

**Issue by zMIMI99** [Lissy93/web-check#58]
Using Raspberry Pi OS 64-bit Lite os.

Get following error: NO matching manifest for linux/arm64/v8.

**Comment by zMIMI99** [comment]
Are there any plans to support ARM64 for this docker image?

**Comment by kynrai** [comment]
the docker image is just node16 buster slim which does have a linux arm64/v8 build

https://hub.docker.com/layers/library/node/16.20.2-buster/images/sha256-9096e122b56e434bfa963f161417cf61637b31d9fdfd5d68c411ceb0d962ffe4?context=explore&tab=vulnerabilities

you can just build it with buildx or specify the --platform param to build if your the pi
