### ISSUE TITLE
How to change fromlocalhost to an ip adress for access the web view

### ISSUE THREAD

**Issue by alfi4000** [Lissy93/web-check#70]
Hi i trieb to change the localhost to a lan interface because I using a server that cannot display anything I am using ubuntu server 22.04.3 but I was unable to change it from localhost to my lan interface!
Can you please help me out with this?   :(

**Comment by kynrai** [comment]
are you running via docker?

**Comment by alfi4000** [comment]
Yeah the prebuilt version I am with yarn and docker etc. unfamiliar but have learn sie basics how people implement the webuis access point like local host access over browser but at this project I wanted to install on a server but can't find the point where the broadcast to localhost goes to change it to one of the servers ip addresses!

**Comment by alfi4000** [comment]
I would be happy if you can help me! :)

**Comment by alfi4000** [comment]
I solved it I just used the repo and the run command and before that I went to App.tsx and added the ip adress I wanted to broadcast over at the section with localhost!

**Comment by alfi4000** [comment]
Yeah
