### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by ajmeese7** [Lissy93/web-check#71]
Is the site down for anyone else? I've tried visiting [web-check.xyz](https://web-check.xyz/) several times today but I'm only greeted with this:

![image](https://github.com/Lissy93/web-check/assets/17814535/ef9cb272-759f-4caa-a317-30712fe89028)

Seems to work fine on the [other link](https://web-check.as93.net/) provided.

**Comment by alfi4000** [comment]
Today it works!

**Comment by Lissy93** [comment]
Hmm, that's weird. But I think in this context `DNS_PROBE_POSSIBLE` will be related to the DNS server you're using. 
I've got an uptime monitoring system running, and it isn't showing that there's been any downtime.
 
If it happens again, let me know, but also check it on something like https://downforeveryoneorjustme.com/

And yes, the .xyz version and .as93.net versions are running on separate hosts, so if one does go down, it shouldn't affect the other.
