### ISSUE TITLE
I have a Question

### ISSUE THREAD

**Issue by alfi4000** [Lissy93/web-check#75]
I have a Question is for this project any future plan to add tools or something?

It would be cool if possible to add like Wpscan to get additional information if the website is Wordpress!

Just a thought!

I am just asking because I am unable to add tools because I don't have any programming skills! :(

**Comment by alfi4000** [comment]
I am not sure if that is even possible!

**Comment by Lissy93** [comment]
I believe WP Scan is capped at 25 API calls per day, so this probably isn't feasible

**Comment by alfi4000** [comment]
Only if using API without api Usage is also possible as far I know I used it several times but every time without the api!

**Comment by alfi4000** [comment]
I looked it up to make sure:   NOTE: You need to provide WPSan with an API Token so that it can look up vulnerabilities infos with https://wpscan.com. Without the token WPScan will only identify WordPress Core / Plugin / Theme versions but not if they are actually vulnerable.


That says google!

**Comment by alfi4000** [comment]
In the most cases in my opinion no API is needed only if someone is trying to hack a website that he would to get more info about!
