### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by hernanpopper** [Lissy93/web-check#79]
Hi! This is absolutely great! 

I am a complete noobie, but hoping to learn! I have some questions, hopefully you can help me.

1) I always get the same errors. Is it something wrong on my side?
![image](https://github.com/Lissy93/web-check/assets/104868017/2d06869b-fc4f-48f3-bda0-3f603a6b880f)

2) I registered and created the APIs as indicated in the readme, but I don't see any changes in the outcome...
![image](https://github.com/Lissy93/web-check/assets/104868017/ef73dd05-ee58-40ae-8086-f0e2ba3614d3)

Thanks so much!

**Comment by hernanpopper** [comment]
I should add that I am using Netlify...  could that be the reason for these issues?

**Comment by Lissy93** [comment]
If you click "Show error" then it should show why a certain check failed.
Without more info, it's not possible to say. Could you share the URL, the server-side logs and the client-side logs?

But it _looks_ like you're API keys aren't present / being read, and/or haven't got headless Chromium working properly.
