### ISSUE TITLE
feature request check if humans.txt exists

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [Lissy93/web-check#8]
https://humanstxt.org/

**Comment by Lissy93** [comment]
Do you know if there is an RFC, formally defined API specification or schema for this?

It wouldn't be hard to add it in, but I've not seen many websites use it, and in order to parse it properly I'd need more of a formal spec than the [humanstxt.org](https://humanstxt.org/) provides.

**Comment by Pierre-Gronau-ndaal** [comment]
I‘m not aware of a RFC …

Where is it located?
In the site root. Just next to the robots.txt file.
If possible, you can also add an author tag to the <head> of the site:
<link type="text/plain" rel="author" href="http://domain/humans.txt" />

alternative you can check https://stackoverflow.com/questions/7067963/where-to-place-the-humans-txt-file-if-i-cannot-put-it-on-the-site-root

the same place like security.txt

**Comment by Lissy93** [comment]
Closing as not a formal standard - less than 0.5% of top 1,000,000 sites implement this, and with no specification the format varies greatly and is subject to change. Will re-open if an RFC for it pops up sometime in the future.
