### ISSUE TITLE
Google and other optional API

### ISSUE THREAD

**Issue by ceaserone** [Lissy93/web-check#80]
I'm jumping the gun here and not doing what I'm supposed as far as looking before asking but trying to take the quick short route, I'm up and running on netlify with no problems, I actually couldn't believe I didn't have ANY errors kickback som bs at me but where can I enter the Google API as well as the other optional API info?

This is really cool and useful thanks wev-check

**Comment by Lissy93** [comment]
Hey @ceaserone, no worries, the Netlify UI is a bit confusing.

You'll need to add environmental variable named `GOOGLE_CLOUD_API_KEY`.

In Netlify specifically, you can add an env var by:
1. Select your Netlify site
2. On the left, click Site Configuration
3. In the secondry left menu, select Environmental Variables

<p align="center"><img width="600" src="https://github.com/Lissy93/web-check/assets/1862727/52fcc858-5598-486b-b9fa-1a681892bb20" /></p>

Then trigger a rebuild, and you should see new results :)

**Comment by ceaserone** [comment]
Thanks lissy worked well
