### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by maurice1408** [Lissy93/web-check#81]
Great work! 

Absolutely minor change but upsets the people with OCD (like me!)

In the intro text you have....

So, **weather** you're a developer, system administrator, security researcher, penetration tester or are just interested in discovering the underlying technologies of a given site - I'm sure you'll find this a useful addition to your toolbox.

Can you change "weather" to "whether"!

**Comment by Lissy93** [comment]
Ha ha, I'm sorry Maurice, spelling never was my strong point (I guess that's why I became a programmer 😆)

Anyway, thanks for pointing that out, I've submitted a fix in 13d0e4ac9f9ba754d38d13c3c338303c1269883a which should go live shortly. 

Have a good day :)
