### ISSUE TITLE
WordPress plugins on nextjs website

### ISSUE THREAD

**Issue by 1NoobDev** [Lissy93/web-check#82]
Not sure if I should put it here.. but I checked my own websites and it says WordPress -plugins 3 live, while it's a nextjs website..

**Comment by Lissy93** [comment]
Interesting,  could you share the URL?

**Comment by 1NoobDev** [comment]
Prefer not as it's an adult content website, not sure if that's allowed to share on github.. I'll send you pm on LinkedIn so you're still able to investigate

**Comment by Lissy93** [comment]
Cool yeah, probz best not to share the link here then 😉

The way the technologies / tech stack widget works, is by comparing the response to known signatures with a massive bunch of RegExs. Here's the list I'm using: https://github.com/Lissy93/wapalyzer/tree/main/src/technologies

It's quite a trivial approach, so it's not impossible for their to be a mistake here, especially if you've copied any code from elsewhere when building your site.

Try scanning your site with BuiltWith (https://builtwith.com/) which uses a similar but slightly different approach. BuiltWith should have more detailed info about what technolgies a site is built with, and how they're detected.

Hope that helps :)
