### ISSUE TITLE
Deploy to Vercel Failing from Master

### ISSUE THREAD

**Issue by kwall1** [Lissy93/web-check#83]
Attempting the 1 click Vercel app seems to fail. Any guidance there?

**Comment by kwall1** [comment]
Error: No more than 12 Serverless Functions can be added to a Deployment on the Hobby plan. Create a team (Pro plan) to deploy more. Learn More: https://vercel.link/function-count-limit

After the build, and rebuilding - I was able to get this error probably because I just tossed it in a free hobby account. I think it's fine as long as you're on a pro account so perhaps close this but it would be good info to anyone who just gives the vercel link a shot on the free plan.

**Comment by Lissy93** [comment]
Hmm, yeah that seems to be the issue. 
Maybe try Vercel instead, they don't have such a limit in place. 
Another option would be to consolidate some of the workers together, so there's under 12 / or just remove the workers that you don't think  you'll need.

**Comment by Lissy93** [comment]
If you expect your instance to get a reasonably large amount of traffic, you might need to think about either upgrading or hosting some of the workers elsewhere to be more cost effective.

For example, I've got some of the heavier jobs running on AWS as lambda functions, for the public instance, as it's a bit cheaper if there's a large volume of users. Still not free though, daily I have 8-10k users per day, and it's costing me about $30/month to run 😑
