### ISSUE TITLE
Traceroute command fails

### ISSUE THREAD

**Issue by slonikappa** [Lissy93/web-check#84]
During url scan, there is an issue with the traceroute command.

Error details:
"The trace-route job failed with an error state after 301 ms. The server responded with the following error:

Command failed: traceroute -q 1 -n some_url
/bin/sh: traceroute: command not found"

**Comment by Lissy93** [comment]
Have you got `traceroute` installed?

**Comment by slonikappa** [comment]
Sorry, I should have clarified that an issue is related to the live demo [web-check.xyz](https://web-check.xyz/) and not self-hosted env

**Comment by Lissy93** [comment]
Ah, that's because traceroute isn't available on Vercel
